export const memes = {
  hot: [
    {
      id: 1,
      title: "hmmmmm",
      author: "Kate",
      upvotes: 6,
      downvotes: 0,
      favorite: true,
      img: "https://www.timecamp.com/blog/wp-content/uploads/2018/02/work-memes-1.jpg",
    },
    {
      id: 4,
      title: "recepta na problemy",
      author: "Brajanusz",
      upvotes: 10,
      downvotes: 3,
      favorite: false,
      img: "https://lalameme.pl/upload/ogloszenie/464/img_1FM0l1NGWtfYLQ.jpg",
    },
    {
      id: 6,
      title: "Grandma is a superhero",
      author: "effigyoma",
      upvotes: 10,
      downvotes: 3,
      favorite: false,
      img: "https://i.kym-cdn.com/photos/images/newsfeed/002/107/882/713.jpg",
    },
  ],
  regular: [
    {
      id: 2,
      title: "Dafuq> WTF",
      author: "Ryba7",
      upvotes: 1,
      downvotes: 2,
      favorite: false,
      img: "https://i.kym-cdn.com/news_feeds/icons/mobile/000/054/894/e1d.jpg",
    },
    {
      id: 3,
      title: "SuPeRmArKeT gUyS aRe IdIoTs",
      author: "Memin-Sanchez",
      upvotes: 3,
      downvotes: 5,
      favorite: false,
      img: "https://i.imgflip.com/5amwr6.jpg",
    },
    {
      id: 5,
      title: "Love These Days",
      author: "MeggyNikirk",
      upvotes: 5,
      downvotes: 5,
      favorite: false,
      img: "https://i.kym-cdn.com/photos/images/newsfeed/002/107/865/59a.jpg",
    },
  ],
};
